// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class LogJob
{
    public long Id { get; set; }

    public string JobName { get; set; }

    public DateTime? JobStart { get; set; }

    public DateTime? JobFinish { get; set; }

    public ulong? Success { get; set; }

    public ulong? Error { get; set; }

    public ulong? Active { get; set; }

    public string Description { get; set; }
}