// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class Menu
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }

    public string Description { get; set; }

    public ulong? IsHeader { get; set; }

    public string Icon { get; set; }

    public ulong? Active { get; set; }

    public int? Sort { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<ProfilMenu> ProfilMenuMenu { get; set; } = new List<ProfilMenu>();

    public virtual ICollection<ProfilMenu> ProfilMenuParentMenu { get; set; } = new List<ProfilMenu>();
}