// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class Message
{
    public long Id { get; set; }

    public long? CompanyId { get; set; }

    public string MessageData { get; set; }

    public ulong? Active { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<SendEmail> SendEmail { get; set; } = new List<SendEmail>();

    public virtual ICollection<SendSms> SendSms { get; set; } = new List<SendSms>();

    public virtual ICollection<SendWhatsapp> SendWhatsapp { get; set; } = new List<SendWhatsapp>();
}