// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class ProductPriceRate
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long ProductTypeId { get; set; }

    public long ProductId { get; set; }

    public long? PriceFrom { get; set; }

    public long? PriceTo { get; set; }

    public int? PercentPrice { get; set; }

    public long? TotalPrice { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Company Company { get; set; }
}