// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class PurchaseOrderDetail
{
    public long Id { get; set; }

    public long? PurchaseHeaderId { get; set; }

    public long? ProductTypeId { get; set; }

    public long? ProductId { get; set; }

    public int? Quantity { get; set; }

    public int? Price { get; set; }

    public long? Subtotal { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductType ProductType { get; set; }

    public virtual PurchaseOrderHeader PurchaseHeader { get; set; }
}