// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class PurchaseOrderHeader
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long BranchId { get; set; }

    public string PurchaseNo { get; set; }

    public DateTime PurchaseDate { get; set; }

    public long SupplierId { get; set; }

    public long? Quantity { get; set; }

    public long? Total { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail { get; set; } = new List<PurchaseOrderDetail>();

    public virtual Supplier Supplier { get; set; }
}