// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class SalesOrderDetail
{
    public long Id { get; set; }

    public long? SalesHeaderId { get; set; }

    public long? ProductTypeId { get; set; }

    public long? ProductId { get; set; }

    public int? Quantity { get; set; }

    public int? Price { get; set; }

    public long? Subtotal { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductType ProductType { get; set; }

    public virtual SalesOrderHeader SalesHeader { get; set; }
}