// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class Supplier
{
    public long Id { get; set; }

    public long? CompanyId { get; set; }

    public long? BranchId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Telp { get; set; }

    public string Fax { get; set; }

    public ulong? Active { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeader { get; set; } = new List<PurchaseOrderHeader>();
}