// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIRetail.Models.Database;

public partial class Users
{
    public long Id { get; set; }

    public long? CompanyId { get; set; }

    public long? BranchId { get; set; }

    public string UserName { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? PasswordExpired { get; set; }

    public string Description { get; set; }

    public ulong? Active { get; set; }

    public DateTime? LastLogin { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<ProfilUser> ProfilUser { get; set; } = new List<ProfilUser>();

    public virtual ICollection<UserToken> UserToken { get; set; } = new List<UserToken>();
}