// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class Clinic
    {
        public Clinic()
        {
            AbsentDoctor = new HashSet<AbsentDoctor>();
            Branch = new HashSet<Branch>();
            Doctor = new HashSet<Doctor>();
            Drug = new HashSet<Drug>();
            ExaminationDoctor = new HashSet<ExaminationDoctor>();
            ExaminationLab = new HashSet<ExaminationLab>();
            ScheduleDoctor = new HashSet<ScheduleDoctor>();
            SpecialistDoctor = new HashSet<SpecialistDoctor>();
            TransactionLab = new HashSet<TransactionLab>();
            Users = new HashSet<Users>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telp { get; set; }
        public string Fax { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual ICollection<AbsentDoctor> AbsentDoctor { get; set; }
        public virtual ICollection<Branch> Branch { get; set; }
        public virtual ICollection<Doctor> Doctor { get; set; }
        public virtual ICollection<Drug> Drug { get; set; }
        public virtual ICollection<ExaminationDoctor> ExaminationDoctor { get; set; }
        public virtual ICollection<ExaminationLab> ExaminationLab { get; set; }
        public virtual ICollection<ScheduleDoctor> ScheduleDoctor { get; set; }
        public virtual ICollection<SpecialistDoctor> SpecialistDoctor { get; set; }
        public virtual ICollection<TransactionLab> TransactionLab { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}