// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class Doctor
    {
        public Doctor()
        {
            AbsentDoctor = new HashSet<AbsentDoctor>();
            ExaminationDoctor = new HashSet<ExaminationDoctor>();
            ScheduleDoctor = new HashSet<ScheduleDoctor>();
        }

        public long Id { get; set; }
        public long? ClinicId { get; set; }
        public long? BranchId { get; set; }
        public string DoctorName { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public string Address { get; set; }
        public string NoTelephone { get; set; }
        public string MobilePhone { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public string StatusEmployee { get; set; }
        public string StatusDoctor { get; set; }
        public ulong? Active { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual ICollection<AbsentDoctor> AbsentDoctor { get; set; }
        public virtual ICollection<ExaminationDoctor> ExaminationDoctor { get; set; }
        public virtual ICollection<ScheduleDoctor> ScheduleDoctor { get; set; }
    }
}