// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class ExaminationLab
    {
        public ExaminationLab()
        {
            TransactionLab = new HashSet<TransactionLab>();
        }

        public long Id { get; set; }
        public long? ClinicId { get; set; }
        public long? BranchId { get; set; }
        public DateTime? ExaminationDate { get; set; }
        public string QueueNo { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual ICollection<TransactionLab> TransactionLab { get; set; }
    }
}