// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class Profil
    {
        public Profil()
        {
            ProfilMenu = new HashSet<ProfilMenu>();
            ProfilUser = new HashSet<ProfilUser>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ulong? Active { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual ICollection<ProfilMenu> ProfilMenu { get; set; }
        public virtual ICollection<ProfilUser> ProfilUser { get; set; }
    }
}