// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class ProfilMenu
    {
        public long Id { get; set; }
        public long? ProfilId { get; set; }
        public long? ParentMenuId { get; set; }
        public long? MenuId { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual Menu ParentMenu { get; set; }
        public virtual Profil Profil { get; set; }
    }
}