// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class SpecialistDoctor
    {
        public SpecialistDoctor()
        {
            PatientRegistration = new HashSet<PatientRegistration>();
            ScheduleDoctor = new HashSet<ScheduleDoctor>();
        }

        public long Id { get; set; }
        public long? ClinicId { get; set; }
        public long? BranchId { get; set; }
        public long? DoctorId { get; set; }
        public long? SpecialistId { get; set; }
        public string Description { get; set; }
        public ulong? Active { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Specialist Specialist { get; set; }
        public virtual ICollection<PatientRegistration> PatientRegistration { get; set; }
        public virtual ICollection<ScheduleDoctor> ScheduleDoctor { get; set; }
    }
}