// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClinic.Models.Database
{
    public partial class Users
    {
        public Users()
        {
            ProfilUser = new HashSet<ProfilUser>();
        }

        public long Id { get; set; }
        public long? ClinicId { get; set; }
        public long? BranchId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime? PasswordExpired { get; set; }
        public string Description { get; set; }
        public ulong? Active { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual ICollection<ProfilUser> ProfilUser { get; set; }
    }
}